apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25Hrs
    trainer: Revanth
  annotations:
    org.docker.kubernetes.image.maintainer: Revanth
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80