#apiVersion: v1
#kind: LimitRange
#metadata:
#  name: cpu-resource-constraint
#spec:
#  limits:
#    - default: # this section defines default limits
#        cpu: 500m
#      defaultRequest: # this section defines default requests
#        cpu: 500m
#      max: # max and min define the limit range
#        cpu: "1"
#      min:
#        cpu: 100m
#      type: Container
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: stress
#spec:
#  containers:
#    - image: revanthsatyam/stress
#      imagePullPolicy: Always
#      name: stress
#      command: ["sleep","200"]
#---
apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - image: revanthsatyam/stress:v1
      imagePullPolicy: Always
      name: stress
      command: ["sleep","200"]
      resources:
        requests: # minimum resource utilization
          memory: "64Mi"
          cpu: "250m" #1cpu=1000m
        limits: # maximum resource utilization
          memory: "128Mi"
          cpu: "500m"